server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # Кэш для ассетов (хэши в именах файлов)
    location ~* \.(js|css|png|jpg|jpeg|gif|svg|ico|woff|woff2|ttf)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    # SPA — любой путь → index.html
    location / {
        try_files $uri $uri/ /index.html;
    }
}
